add oidc

diff --git a/azure-pipelines.yml b/azure-pipelines.yml
--- a/azure-pipelines.yml
+++ b/azure-pipelines.yml
@@ -19,23 +19,25 @@ steps:
   #       echo $(System.AccessToken) | az devops login
   #   env:
   #     SYSTEM_ACCESSTOKEN: $(System.AccessToken)
-  - task: AzureCLI@2
-    displayName: Terraform credentials
-    inputs:
-      azureSubscription: "Azure Subs OIDC"
-      scriptLocation: inlineScript
-      scriptType: bash
-      inlineScript: |
-        set -eu  # fail on error
-        az account set -s $(subscription_id)
-        subscriptionId=$(az account show --query id -o tsv)
-        echo "##vso[task.setvariable variable=ARM_CLIENT_ID]$servicePrincipalId"
-        echo "##vso[task.setvariable variable=ARM_USE_OIDC]true"
-        echo "##vso[task.setvariable variable=ARM_OIDC_TOKEN]$idToken"
-        echo "##vso[task.setvariable variable=ARM_TENANT_ID]$tenantId"
-      addSpnToEnvironment: true
+  # - task: AzureCLI@2
+  #   displayName: Terraform credentials
+  #   inputs:
+  #     azureSubscription: "Azure Subs OIDC"
+  #     scriptLocation: inlineScript
+  #     scriptType: bash
+  #     inlineScript: |
+  #       set -eu  # fail on error
+  #       az account set -s $(subscription_id)
+  #       subscriptionId=$(az account show --query id -o tsv)
+  #       echo "##vso[task.setvariable variable=ARM_CLIENT_ID]$servicePrincipalId"
+  #       echo "##vso[task.setvariable variable=ARM_USE_OIDC]true"
+  #       echo "##vso[task.setvariable variable=ARM_OIDC_TOKEN]$idToken"
+  #       echo "##vso[task.setvariable variable=ARM_TENANT_ID]$tenantId"
+  #     addSpnToEnvironment: true
 
   - script: |
+
+      az devops login --organization https://dev.azure.com/josielbruk/ --token $(System.AccessToken)
       az artifacts universal download \
       --organization "https://dev.azure.com/josielbruk/" \
       --feed "josielbruk" \
