add oidc

diff --git a/azure-pipelines.yml b/azure-pipelines.yml
--- a/azure-pipelines.yml
+++ b/azure-pipelines.yml
@@ -19,6 +19,22 @@ steps:
         echo $(System.AccessToken) | az devops login
     env:
       SYSTEM_ACCESSTOKEN: $(System.AccessToken)
+  - task: AzureCLI@2
+    displayName: Terraform credentials
+    inputs:
+      azureSubscription: ${{ parameters.serviceConnection }}
+      scriptLocation: inlineScript
+      scriptType: bash
+      inlineScript: |
+        set -eu  # fail on error
+        az account set -s $(subscription_id)
+        subscriptionId=$(az account show --query id -o tsv)
+        echo "##vso[task.setvariable variable=ARM_CLIENT_ID]$servicePrincipalId"
+        echo "##vso[task.setvariable variable=ARM_USE_OIDC]true"
+        echo "##vso[task.setvariable variable=ARM_OIDC_TOKEN]$idToken"
+        echo "##vso[task.setvariable variable=ARM_SUBSCRIPTION_ID]$subscriptionId"
+        echo "##vso[task.setvariable variable=ARM_TENANT_ID]$tenantId"
+      addSpnToEnvironment: true
 
   - script: |
       az artifacts universal download \
